spring.application.name=GymChatService
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gymmanagment
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# JWT Secret (Should match other services if sharing token, matches the one found in GymUserManagement)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
