-- V22__seed_comprehensive_workout_database.sql
-- Add detailed workout attributes to exercises table and seed 10+ exercises per muscle group

ALTER TABLE exercises
    ADD COLUMN IF NOT EXISTS secondary_muscles VARCHAR(255),
    ADD COLUMN IF NOT EXISTS equipment VARCHAR(255),
    ADD COLUMN IF NOT EXISTS mechanics VARCHAR(255),
    ADD COLUMN IF NOT EXISTS difficulty_level VARCHAR(255),
    ADD COLUMN IF NOT EXISTS recommended_sets INTEGER,
    ADD COLUMN IF NOT EXISTS recommended_reps VARCHAR(255),
    ADD COLUMN IF NOT EXISTS rest_interval VARCHAR(255),
    ADD COLUMN IF NOT EXISTS execution_steps TEXT,
    ADD COLUMN IF NOT EXISTS safety_tips TEXT;

-- Clear mock exercises to avoid duplicate key or outdated structure
DELETE FROM exercises WHERE id IS NOT NULL;

-- ── CHEST (10 EXERCISES) ──────────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '11111111-1111-1111-1111-111111111101',
    'Barbell Bench Press',
    'CHEST',
    'Triceps, Front Delts',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-10', '90-120s',
    'The king of upper body chest builders targeting mid and lower chest fibers.',
    '1. Lie flat on bench with feet flat on floor.\n2. Grip barbell wider than shoulder-width.\n3. Unrack bar and lower under control to mid-chest.\n4. Press bar upward explosively aligning wrists directly over elbows.',
    'Keep your feet planted and arch upper back slightly. Avoid flaring elbows out at 90°; tuck them to 45° to protect shoulder joints.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111102',
    'Incline Dumbbell Press',
    'CHEST',
    'Upper Chest, Front Delts, Triceps',
    'Dumbbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '10-12', '90s',
    'Targets upper clavicular chest head for high chest volume.',
    '1. Set incline bench angle to 30-45 degrees.\n2. Sit down, place dumbbells on thighs, and kick them up to shoulder level.\n3. Press dumbbells upward until arms are almost locked out.\n4. Lower dumbbells slowly under control past chest level.',
    'Do not set bench higher than 45° to avoid shifting tension away from chest onto front shoulders.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111103',
    'Decline Barbell Press',
    'CHEST',
    'Lower Chest, Triceps',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    3, '8-12', '90s',
    'Emphasizes the sternal and lower chest sweep.',
    '1. Secure feet in decline bench leg rolls.\n2. Grip barbell at shoulder-width.\n3. Unrack bar and lower steadily to lower chest/upper abdomen.\n4. Drive bar upward to starting position.',
    'Always use a spotter when performing decline barbell press due to safety risks racking above head.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111104',
    'Chest Dips (Bodyweight/Weighted)',
    'CHEST',
    'Triceps, Front Delts',
    'Bodyweight',
    'COMPOUND',
    'PRO',
    4, '8-12', '90s',
    'High-intensity lower chest and tricep compound movement.',
    '1. Grab parallel dip bars and suspend body.\n2. Lean torso forward at a 30-degree angle with legs bent back.\n3. Lower body until shoulders are below elbows.\n4. Press back up until arms are fully extended.',
    'Avoid dipping too deep if you experience anterior shoulder pain. Maintain forward torso lean throughout.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111105',
    'Standing Cable Chest Flyes',
    'CHEST',
    'Inner Chest, Front Delts',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '60s',
    'Continuous cable tension across the full chest range of motion.',
    '1. Set cable pulleys at shoulder height and take a step forward in staggered stance.\n2. Maintain slight bend in elbows.\n3. Squeeze chest to bring handles together in front of sternum.\n4. Slowly open chest until stretch is felt.',
    'Keep core tight and avoid swinging torso to propel weights forward.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111106',
    'Pec Deck Machine Fly',
    'CHEST',
    'Inner Chest',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '60s',
    'Strict machine isolation for peak chest squeeze.',
    '1. Adjust seat height so handles align with mid-chest.\n2. Keep back flat against pad and elbows slightly bent.\n3. Pull handles together in smooth arc until they touch.\n4. Pause for 1 second, then control return movement.',
    'Keep scapula retracted and depressed into seat back pad throughout execution.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111107',
    'Incline Cable Press',
    'CHEST',
    'Upper Chest, Triceps',
    'Cable',
    'COMPOUND',
    'INTERMEDIATE',
    3, '10-12', '75s',
    'Upper chest builder with uniform resistance curves.',
    '1. Place incline bench between low cable pulleys.\n2. Grab D-handles and sit back on bench.\n3. Press cables upward and inward above upper chest.\n4. Lower back under control.',
    'Maintain 45° arm alignment relative to torso.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111108',
    'Dumbbell Chest Pullover',
    'CHEST',
    'Lats, Serratus Anterior',
    'Dumbbell',
    'ISOLATION',
    'INTERMEDIATE',
    3, '10-12', '60s',
    'Expands ribcage and targets upper chest and serratus.',
    '1. Lie perpendicular across flat bench with upper back supported.\n2. Hold single dumbbell overhead with palms flat under top plate.\n3. Lower dumbbell back behind head while keeping arms slightly bent.\n4. Pull dumbbell back up over chest using chest and lats.',
    'Do not let hips drop down; keep glutes squeezed and core engaged.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111109',
    'Standard Floor Push-Ups',
    'CHEST',
    'Triceps, Core, Front Delts',
    'Bodyweight',
    'COMPOUND',
    'BEGINNER',
    4, '15-20', '60s',
    'Fundamental bodyweight push movement for all fitness levels.',
    '1. Place hands slightly wider than shoulder-width on floor.\n2. Keep body in rigid straight plank position from head to heels.\n3. Lower chest until 1 inch off floor.\n4. Press floor away to return to top.',
    'Prevent hips from sagging or piking up. Engage abdominal wall.',
    NOW()
),
(
    '11111111-1111-1111-1111-111111111110',
    'Low-to-High Cable Fly',
    'CHEST',
    'Upper Chest, Front Delts',
    'Cable',
    'ISOLATION',
    'INTERMEDIATE',
    3, '12-15', '60s',
    'Scans upward trajectory to isolate upper chest fibers.',
    '1. Set pulleys at lowest position on cable stack.\n2. Stand in middle, palms facing forward.\n3. Sweep handles upward and inward towards eye level.\n4. Squeeze upper chest at top for 1 second before lowering.',
    'Do not use momentum or shrug shoulders upward during sweep.',
    NOW()
);

-- ── BACK (10 EXERCISES) ───────────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '22222222-2222-2222-2222-222222222201',
    'Conventional Barbell Deadlift',
    'BACK',
    'Hamstrings, Glutes, Forearms, Erector Spinae',
    'Barbell',
    'COMPOUND',
    'PRO',
    4, '5-6', '120-180s',
    'Full body posterior chain strength builder.',
    '1. Stand with feet hip-width under barbell.\n2. Hinge at hips to grip bar just outside knees.\n3. Flatten back, pull slack out of bar, and drive feet into floor.\n4. Stand tall locking out hips and knees simultaneously.',
    'Never round lumbar spine. Keep bar close to shins and thighs throughout lift.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222202',
    'Wide-Grip Lat Pulldown',
    'BACK',
    'Biceps, Rear Delts',
    'Cable',
    'COMPOUND',
    'BEGINNER',
    4, '10-12', '90s',
    'Builds back width and lats.',
    '1. Sit at pulldown machine and adjust thigh pads securely.\n2. Grip wide bar with overhand grip.\n3. Pull bar down to upper chest while driving elbows down.\n4. Slowly return bar under full stretch.',
    'Do not swing torso back dramatically or pull bar behind neck.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222203',
    'Bent-Over Barbell Row',
    'BACK',
    'Rhomboids, Lats, Biceps',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-10', '90s',
    'Mass builder for mid-back thickness.',
    '1. Hinge hips at 45-degree angle with flat back holding barbell.\n2. Pull barbell towards lower ribcage/navel.\n3. Squeeze shoulder blades together at top.\n4. Lower bar with full arm extension.',
    'Maintain flat spine alignment; avoid jerking weight up using legs.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222204',
    'Seated Cable Row (Close Grip)',
    'BACK',
    'Rhomboids, Lower Lats',
    'Cable',
    'COMPOUND',
    'BEGINNER',
    4, '10-12', '75s',
    'Mid-back thickness and seated control.',
    '1. Sit with feet on footplates, knees slightly flexed.\n2. Grab V-bar handle and sit upright.\n3. Pull handle to stomach while driving elbows back.\n4. Release forward stretching lats.',
    'Avoid leaning excessively forward or backward during repetitions.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222205',
    'Single-Arm Dumbbell Row',
    'BACK',
    'Lats, Biceps',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    3, '10-12', '60s',
    'Unilateral lat builder allowing deep stretch and contraction.',
    '1. Place left knee and hand on flat bench.\n2. Hold dumbbell in right hand with extended arm.\n3. Pull dumbbell to hip pocket keeping elbow close to torso.\n4. Lower down fully.',
    'Keep hips level and avoid twisting torso at top of stroke.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222206',
    'Bodyweight Pull-Ups',
    'BACK',
    'Lats, Biceps, Core',
    'Bodyweight',
    'COMPOUND',
    'INTERMEDIATE',
    4, '6-10', '90s',
    'Ultimate bodyweight vertical pulling movement.',
    '1. Hang from pull-up bar with overhand grip wider than shoulders.\n2. Depress shoulder blades and pull chin above bar.\n3. Lower down under control to dead hang.',
    'Avoid kicking legs or swinging body to achieve pull height.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222207',
    'T-Bar Chest-Supported Row',
    'BACK',
    'Mid-Back, Traps, Lats',
    'Machine',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-12', '90s',
    'Heavy back rower without lower back strain.',
    '1. Rest chest on pad and grab handles.\n2. Pull handles up squeezing upper back.\n3. Pause briefly at peak contraction.\n4. Lower weight smoothly.',
    'Keep chest firmly planted against pad throughout entire set.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222208',
    'Face Pulls (Rope Cable)',
    'BACK',
    'Rear Delts, Rhomboids, External Rotators',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '15-20', '60s',
    'Essential shoulder health and rear upper back exercise.',
    '1. Attach rope to upper pulley on cable machine.\n2. Hold rope ends with thumbs pointing back.\n3. Pull handles towards eyes while spreading hands apart.\n4. Hold contraction 1-2 seconds.',
    'Focus on quality high-rep contraction rather than heavy weight.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222209',
    'Straight-Arm Cable Pushdown',
    'BACK',
    'Lats, Teres Major',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '60s',
    'Isolates lats without bicep fatigue.',
    '1. Stand facing cable pulley with straight bar attached at top.\n2. Grab bar with slight arm bend and push bar down to thighs in sweeping arc.\n3. Control bar back up to eye level.',
    'Keep elbows rigid at slight angle; do not turn into tricep pushdown.',
    NOW()
),
(
    '22222222-2222-2222-2222-222222222210',
    'Hyperextensions (Back Extension)',
    'BACK',
    'Lower Back, Glutes, Hamstrings',
    'Machine',
    'COMPOUND',
    'BEGINNER',
    3, '12-15', '60s',
    'Strengthens lower back erector spinae.',
    '1. Lock legs into 45-degree hyperextension bench.\n2. Cross arms over chest or hold weight plate.\n3. Lower torso down by bending at waist.\n4. Raise torso until body is straight inline with legs.',
    'Do not hyperextend spine excessively past straight alignment at top.',
    NOW()
);

-- ── SHOULDERS (10 EXERCISES) ──────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '33333333-3333-3333-3333-333333333301',
    'Overhead Barbell Military Press',
    'SHOULDERS',
    'Front Delts, Triceps, Upper Chest',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '6-8', '120s',
    'The premier shoulder mass builder for front delts.',
    '1. Stand tall holding barbell at collarbone level with shoulder-width grip.\n2. Squeeze glutes and core tight.\n3. Press bar vertically overhead locking out overhead.\n4. Lower bar smoothly back to shoulders.',
    'Avoid leaning backwards significantly. Keep glutes squeezed tight.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333302',
    'Seated Dumbbell Shoulder Press',
    'SHOULDERS',
    'Front & Lateral Delts, Triceps',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    4, '8-12', '90s',
    'Heavy shoulder press with free range of motion.',
    '1. Sit on vertical 90-degree bench holding dumbbells at ear level.\n2. Press dumbbells upward until overhead.\n3. Lower dumbbells under control back to ear level.',
    'Keep palms angled at 45 degrees inwards to protect rotator cuff.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333303',
    'Arnold Press',
    'SHOULDERS',
    'Front, Side, Rear Delts',
    'Dumbbell',
    'COMPOUND',
    'INTERMEDIATE',
    3, '10-12', '75s',
    'Rotational dumbbell press hitting all three shoulder heads.',
    '1. Hold dumbbells in front of chest with palms facing inwards.\n2. As you press upward, rotate wrists outwards until palms face forward at top.\n3. Reverse rotation on descent.',
    'Use controlled smooth motion throughout rotation.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333304',
    'Dumbbell Lateral Raises',
    'SHOULDERS',
    'Side Delts',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    4, '12-15', '60s',
    'Builds shoulder width and 3D lateral delt look.',
    '1. Stand holding dumbbells at sides with slight elbow bend.\n2. Raise dumbbells out to sides until parallel with floor.\n3. Lower down under control.',
    'Lead with elbows and avoid shrugging shoulders up to ears.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333305',
    'Cable Side Lateral Raise',
    'SHOULDERS',
    'Side Delts',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '60s',
    'Continuous cable tension across lateral head.',
    '1. Stand next to low cable pulley, grab handle behind body.\n2. Raise cable handle out laterally to shoulder level.\n3. Control return path.',
    'Keep arm fixed in slight elbow flexed position.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333306',
    'Front Dumbbell Raise',
    'SHOULDERS',
    'Front Delts',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '60s',
    'Direct anterior delt isolation exercise.',
    '1. Stand holding dumbbells on front of thighs.\n2. Raise one dumbbell straight up in front to eye height.\n3. Lower down and alternate sides.',
    'Avoid swinging torso backward.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333307',
    'Reverse Pec Deck (Rear Delt Fly)',
    'SHOULDERS',
    'Rear Delts, Upper Traps',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    4, '12-15', '60s',
    'Isolates posterior delt head.',
    '1. Sit facing pec deck machine with chest against pad.\n2. Grab handles and push arms outward in horizontal arc.\n3. Squeeze rear delts at peak.',
    'Keep shoulders down away from ears.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333308',
    'Barbell Shrugs',
    'SHOULDERS',
    'Trapezius',
    'Barbell',
    'ISOLATION',
    'BEGINNER',
    4, '10-12', '60s',
    'Builds upper trap thickness.',
    '1. Hold heavy barbell at arm length.\n2. Elevate shoulders straight up towards ears.\n3. Squeeze traps at top for 1 second before lowering.',
    'Do not roll shoulders in circles; elevate straight up and down.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333309',
    'Upright Barbell Row',
    'SHOULDERS',
    'Side Delts, Traps',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    3, '10-12', '75s',
    'Pulls bar vertically close to body for shoulder width.',
    '1. Hold barbell with shoulder-width overhand grip.\n2. Pull bar straight up close to torso leading with elbows.\n3. Stop when elbows reach shoulder level.',
    'Do not pull bar above chest level to prevent shoulder impingement.',
    NOW()
),
(
    '33333333-3333-3333-3333-333333333310',
    'Bent-Over Rear Delt Cable Fly',
    'SHOULDERS',
    'Rear Delts',
    'Cable',
    'ISOLATION',
    'INTERMEDIATE',
    3, '15-20', '60s',
    'Cross-cable rear delt flies.',
    '1. Stand between low cable pulleys, grab left handle with right hand and vice versa.\n2. Bend forward at waist, pull cables apart in wide arc.\n3. Squeeze rear delts.',
    'Keep back flat and hips stable.',
    NOW()
);

-- ── BICEPS (10 EXERCISES) ─────────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '44444444-4444-4444-4444-444444444401',
    'Standing Barbell Bicep Curl',
    'BICEPS',
    'Brachialis, Forearms',
    'Barbell',
    'ISOLATION',
    'BEGINNER',
    4, '8-10', '75s',
    'The foundational bicep mass builder.',
    '1. Stand upright holding barbell with underhand grip at shoulder-width.\n2. Keep elbows pinned to sides.\n3. Curl bar up towards chest.\n4. Lower down with full arm extension.',
    'Do not swing torso back or move elbows forward while curling.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444402',
    'Incline Dumbbell Curl',
    'BICEPS',
    'Biceps Long Head (Peak)',
    'Dumbbell',
    'ISOLATION',
    'INTERMEDIATE',
    3, '10-12', '60s',
    'Deep bicep stretch targeting the long head peak.',
    '1. Sit back on 45-degree incline bench with dumbbells hanging down.\n2. Curl dumbbells up supinating wrists (palms up at top).\n3. Lower down under stretch.',
    'Keep back and shoulders flat against bench pad.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444403',
    'EZ-Bar Preacher Curl',
    'BICEPS',
    'Biceps Short Head',
    'Barbell',
    'ISOLATION',
    'BEGINNER',
    4, '10-12', '60s',
    'Strict bicep isolation eliminating body momentum.',
    '1. Position armpits against preacher bench pad holding EZ-bar.\n2. Lower bar down until arms are almost straight.\n3. Curl bar up to chin level squeezing biceps.',
    'Do not snap elbows into full extension at bottom under heavy weight.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444404',
    'Neutral Grip Hammer Curls',
    'BICEPS',
    'Brachialis, Forearms (Brachioradialis)',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    4, '10-12', '60s',
    'Builds arm thickness and forearm size.',
    '1. Stand holding dumbbells with palms facing each other (neutral grip).\n2. Curl dumbbells up without twisting wrists.\n3. Lower down steadily.',
    'Maintain rigid neutral wrist alignment throughout.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444405',
    'Concentration Dumbbell Curls',
    'BICEPS',
    'Biceps Peak',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '45s',
    'Peak bicep contraction isolation exercise.',
    '1. Sit on bench, rest elbow against inner thigh.\n2. Curl dumbbell up towards face.\n3. Squeeze bicep intensely at top.',
    'Keep upper arm stationary against inner thigh.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444406',
    'Cable Rope Bicep Curls',
    'BICEPS',
    'Brachialis, Forearms',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '60s',
    'Continuous rope cable tension.',
    '1. Attach rope to low cable stack.\n2. Hold rope ends with neutral grip.\n3. Curl up and spread rope ends apart at top peak contraction.',
    'Keep shoulders back and elbows locked in place.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444407',
    'EZ-Bar Spider Curls',
    'BICEPS',
    'Biceps Short Head',
    'Barbell',
    'ISOLATION',
    'INTERMEDIATE',
    3, '10-12', '60s',
    'Chest supported vertical bicep builder.',
    '1. Lie chest down on incline bench holding EZ-bar hanging vertically.\n2. Curl bar straight up.\n3. Lower under full extension control.',
    'Allows zero momentum cheat; strict tension.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444408',
    'High Cable Overhead Curls',
    'BICEPS',
    'Biceps Peak',
    'Cable',
    'ISOLATION',
    'INTERMEDIATE',
    3, '12-15', '60s',
    'Double bicep pose cable flex.',
    '1. Stand between high cable stacks holding D-handles.\n2. Curl handles inward towards ears in double-bicep pose stance.\n3. Squeeze 1 second.',
    'Keep upper arms parallel to floor.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444409',
    'Zottman Dumbbell Curls',
    'BICEPS',
    'Biceps & Forearm Extensors',
    'Dumbbell',
    'ISOLATION',
    'INTERMEDIATE',
    3, '10-12', '60s',
    'Dual bicep and forearm developer.',
    '1. Curl dumbbells up palms facing up.\n2. At top, rotate palms 180 degrees to face down.\n3. Lower dumbbells down under pronated overhand grip.',
    'Controls forearm loading on eccentric drop.',
    NOW()
),
(
    '44444444-4444-4444-4444-444444444410',
    'Drag Barbell Curls',
    'BICEPS',
    'Biceps Short Head',
    'Barbell',
    'ISOLATION',
    'INTERMEDIATE',
    3, '10-12', '60s',
    'Drags bar vertically up torso line.',
    '1. Hold barbell at thighs.\n2. Drive elbows backward while dragging bar directly along front of torso.\n3. Lower down maintaining contact.',
    'Removes front delt involvement completely.',
    NOW()
);

-- ── TRICEPS (10 EXERCISES) ────────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '55555555-5555-5555-5555-555555555501',
    'Tricep Rope Cable Pushdown',
    'TRICEPS',
    'Triceps Lateral & Medial Head',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    4, '10-12', '60s',
    'Popular tricep builder targeting lateral outer head.',
    '1. Attach rope to top cable pulley.\n2. Hold handles with elbows tucked into ribcage.\n3. Push rope down and spread handles outward at bottom extension.\n4. Slowly return up to 90 degrees.',
    'Do not flare elbows or let shoulders roll forward.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555502',
    'Close-Grip Barbell Bench Press',
    'TRICEPS',
    'Chest, Front Delts',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '6-8', '90s',
    'Heavy tricep compound strength exercise.',
    '1. Lie on bench holding barbell with shoulder-width grip.\n2. Lower bar to lower chest while keeping elbows tucked close to torso.\n3. Press weight straight back up locking out triceps.',
    'Do not place hands too close together (under 8 inches) to avoid wrist strain.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555503',
    'Skull Crushers (EZ-Bar Extension)',
    'TRICEPS',
    'Triceps Long Head',
    'Barbell',
    'ISOLATION',
    'INTERMEDIATE',
    4, '8-10', '75s',
    'Classic mass builder for the long head of the triceps.',
    '1. Lie on flat bench holding EZ-bar overhead with narrow grip.\n2. Lower bar down towards forehead by bending at elbows.\n3. Extend arms back up to starting position.',
    'Keep upper arms stationary angled slightly back behind forehead to protect elbows.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555504',
    'Overhead Rope Tricep Extension',
    'TRICEPS',
    'Triceps Long Head',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '60s',
    'Stretches long head under cable tension.',
    '1. Attach rope to cable stack and face away from machine.\n2. Hold rope behind head with elbows pointed forward.\n3. Extend arms overhead until fully locked out.',
    'Keep core engaged and avoid arching lower spine.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555505',
    'Parallel Bar Tricep Dips',
    'TRICEPS',
    'Chest, Front Delts',
    'Bodyweight',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-12', '90s',
    'Bodyweight tricep extension movement.',
    '1. Mount dip station upright with arms straight.\n2. Lower body vertically keeping torso upright (no forward lean).\n3. Push back up to top extension.',
    'Keep torso upright to emphasize triceps over chest.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555506',
    'Diamond Push-Ups',
    'TRICEPS',
    'Chest, Core',
    'Bodyweight',
    'COMPOUND',
    'BEGINNER',
    3, '12-15', '60s',
    'Bodyweight tricep burner exercise.',
    '1. Form diamond shape with thumbs and index fingers on floor under chest.\n2. Lower chest down to touch hands.\n3. Press up to lockout.',
    'Keep body in straight plank.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555507',
    'Single-Arm Reverse Cable Pushdown',
    'TRICEPS',
    'Triceps Medial Head',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '45s',
    'Underhand grip cable isolation.',
    '1. Hold single cable D-handle with underhand (supinated) grip.\n2. Push handle straight down extending elbow.\n3. Return slowly.',
    'Isolates medial head.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555508',
    'Dumbbell Tricep Kickbacks',
    'TRICEPS',
    'Triceps Lateral Head',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '45s',
    'Peak contraction isolation.',
    '1. Hinge at waist with knee on bench.\n2. Raise upper arm parallel to torso.\n3. Extend dumbbell back until arm is straight.',
    'Keep upper arm fixed parallel to ground.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555509',
    'Seated Overhead Dumbbell Extension',
    'TRICEPS',
    'Triceps Long Head',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    3, '10-12', '60s',
    'Heavy single dumbbell overhead stretch.',
    '1. Sit upright holding heavy dumbbell overhead in both hands.\n2. Lower dumbbell behind head towards neck.\n3. Press back up to lockout.',
    'Keep elbows tucked in towards ears.',
    NOW()
),
(
    '55555555-5555-5555-5555-555555555510',
    'Bench Dips',
    'TRICEPS',
    'Front Delts',
    'Bodyweight',
    'COMPOUND',
    'BEGINNER',
    3, '15-20', '45s',
    'Accessible tricep bodyweight exercise.',
    '1. Place hands on edge of flat bench behind hips, feet out front.\n2. Lower hips down bending elbows to 90 degrees.\n3. Press back up.',
    'Keep back close to bench edge.',
    NOW()
);

-- ── ABS / CORE (10 EXERCISES) ─────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '66666666-6666-6666-6666-666666666601',
    'Hanging Leg Raises',
    'ABS',
    'Lower Abs, Hip Flexors',
    'Bodyweight',
    'ISOLATION',
    'INTERMEDIATE',
    4, '12-15', '60s',
    'Premier lower abdominal builder.',
    '1. Hang from pull-up bar with overhand grip.\n2. Raise legs straight up to 90 degrees or touch toes to bar.\n3. Lower down slowly under control.',
    'Avoid swinging body for momentum.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666602',
    'Kneeling Cable Ab Crunch',
    'ABS',
    'Upper Abs',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    4, '15-20', '60s',
    'Weighted progressive overload ab crunch.',
    '1. Kneel facing cable stack holding rope handles at temples.\n2. Flex spine downward bringing elbows to knees.\n3. Squeeze abs tight at bottom.',
    'Pull with abdominal wall, not arms or hips.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666603',
    'Ab Wheel Rollouts',
    'ABS',
    'Full Core, Lats, Lower Back',
    'Bodyweight',
    'COMPOUND',
    'PRO',
    4, '8-10', '75s',
    'High-intensity core stability exercise.',
    '1. Kneel on pad holding ab wheel roller.\n2. Roll wheel forward keeping core bracing straight.\n3. Pull back to starting position using abs.',
    'Do not let lower back arch down toward floor.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666604',
    'Weighted Russian Twists',
    'ABS',
    'Obliques, Core',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    3, '20', '45s',
    'Rotational oblique strengthener.',
    '1. Sit on floor with knees bent and feet elevated.\n2. Hold weight plate or dumbbell at chest.\n3. Twist torso side to side touching weight near floor.',
    'Keep spine upright.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666605',
    'Decline Bench Crunches',
    'ABS',
    'Upper Abs',
    'Bodyweight',
    'ISOLATION',
    'BEGINNER',
    3, '15-20', '60s',
    'Increased gravity resistance crunch.',
    '1. Hook feet into decline bench.\n2. Curl torso up off pad squeezing upper abdominal wall.\n3. Lower back down under control.',
    'Do not pull on neck with hands.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666606',
    'Forearm Plank Hold',
    'ABS',
    'Transverse Abdominis, Core, Shoulders',
    'Bodyweight',
    'ISOLATION',
    'BEGINNER',
    4, '60s Hold', '45s',
    'Isometric core endurance plank.',
    '1. Support body on forearms and toes.\n2. Maintain rigid straight body posture.\n3. Brace abs continuously.',
    'Keep hips inline with shoulders.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666607',
    'Mountain Climbers',
    'ABS',
    'Lower Abs, Cardio',
    'Bodyweight',
    'COMPOUND',
    'BEGINNER',
    3, '30s Burst', '30s',
    'Dynamic ab and cardiovascular conditioning.',
    '1. Start in high push-up plank stance.\n2. Rapidly drive alternating knees towards chest.',
    'Keep hips down.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666608',
    'Bicycle Crunches',
    'ABS',
    'Obliques & Rectus Abdominis',
    'Bodyweight',
    'ISOLATION',
    'BEGINNER',
    3, '20-25', '45s',
    'Cross-body oblique crunch.',
    '1. Lie on back with legs off ground.\n2. Rotate opposite elbow to opposite knee in rhythmic bicycle movement.',
    'Smooth controlled rotation.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666609',
    'Reverse Crunches',
    'ABS',
    'Lower Abs',
    'Bodyweight',
    'ISOLATION',
    'BEGINNER',
    3, '15-20', '45s',
    'Lifting hips off floor.',
    '1. Lie flat on back with arms at sides.\n2. Flex knees and lift hips up off floor pulling knees to chest.',
    'Control descent.',
    NOW()
),
(
    '66666666-6666-6666-6666-666666666610',
    'Captain Chair Knee Raises',
    'ABS',
    'Lower Abs',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '45s',
    'Supported lower ab raise.',
    '1. Rest forearms on captain chair pads.\n2. Drive knees up to chest squeezing lower abs.',
    'Avoid swinging legs.',
    NOW()
);

-- ── QUADS & LEGS (10 EXERCISES) ───────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '77777777-7777-7777-7777-777777777701',
    'Barbell Back Squats',
    'QUADS',
    'Glutes, Hamstrings, Core, Lower Back',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-10', '120-180s',
    'The king of leg exercises for full leg growth.',
    '1. Rest barbell across upper traps.\n2. Stand with feet shoulder-width apart.\n3. Squat down by pushing hips back and bending knees past parallel.\n4. Drive up through heels.',
    'Keep chest up and knees tracking over toes.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777702',
    'Front Barbell Squats',
    'QUADS',
    'Glutes, Upper Back, Core',
    'Barbell',
    'COMPOUND',
    'PRO',
    4, '6-8', '120s',
    'Quad-dominant squat with vertical torso posture.',
    '1. Rest bar on front anterior delts with fingertip or cross-arm grip.\n2. Keep elbows high parallel to floor.\n3. Squat deep and press up.',
    'Keep chest proud and elbows high.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777703',
    '45-Degree Leg Press',
    'QUADS',
    'Glutes, Hamstrings',
    'Machine',
    'COMPOUND',
    'BEGINNER',
    4, '10-12', '90s',
    'Heavy leg overload machine.',
    '1. Sit in leg press machine with feet shoulder-width on sled platform.\n2. Release safety latches and lower sled until knees form 90 degrees.\n3. Press sled back up.',
    'Do not lock knees out forcefully at top; keep slight bend.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777704',
    'Bulgarian Split Squats',
    'QUADS',
    'Glutes, Hamstrings',
    'Dumbbell',
    'COMPOUND',
    'INTERMEDIATE',
    3, '10-12', '75s',
    'Unilateral leg mass and balance developer.',
    '1. Place rear foot elevated on flat bench behind you.\n2. Lower hips straight down until front thigh is parallel to ground.\n3. Drive up through front heel.',
    'Keep torso upright for quad emphasis.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777705',
    'Dumbbell Walking Lunges',
    'QUADS',
    'Glutes, Calves',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    3, '12-15 steps', '60s',
    'Dynamic walking leg strength exercise.',
    '1. Hold dumbbells at sides.\n2. Step forward into lunge dipping back knee near ground.\n3. Drive off front heel into next step.',
    'Maintain upright posture.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777706',
    'Leg Extension Machine',
    'QUADS',
    'Rectus Femoris',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    4, '12-15', '60s',
    'Direct quad teardrop isolation.',
    '1. Sit in machine with pad positioned against lower shins.\n2. Extend legs up until quads are fully contracted.\n3. Lower down smoothly.',
    'Align knee joint with machine pivot axis.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777707',
    'Hack Squat Machine',
    'QUADS',
    'Glutes',
    'Machine',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-10', '90s',
    'Fixed sled quad builder.',
    '1. Position shoulders under pads on hack squat machine.\n2. Squat down to 90 degrees.\n3. Press sled back up.',
    'Keep lower back flush against back pad.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777708',
    'Goblet Dumbbell Squats',
    'QUADS',
    'Core, Glutes',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    3, '12-15', '60s',
    'Beginner-friendly squat pattern.',
    '1. Hold single heavy dumbbell vertically at chest.\n2. Squat down between knees.\n3. Press back up.',
    'Great for learning deep squat form.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777709',
    'Sissy Squats (Bodyweight/Weighted)',
    'QUADS',
    'Rectus Femoris Stretch',
    'Bodyweight',
    'ISOLATION',
    'PRO',
    3, '10-12', '60s',
    'Quad stretch and peak tension.',
    '1. Hold support bar, lean torso backward while pushing knees forward.\n2. Lower down stretching quads.\n3. Drive up.',
    'Proceed carefully if history of knee pain.',
    NOW()
),
(
    '77777777-7777-7777-7777-777777777710',
    'Box Step-Ups',
    'QUADS',
    'Glutes',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    3, '10-12', '60s',
    'Unilateral box drive.',
    '1. Stand in front of knee-high plyo box holding dumbbells.\n2. Step foot firmly onto box and drive body up.\n3. Step down under control.',
    'Do not push off bottom foot; drive through top leg.',
    NOW()
);

-- ── HAMSTRINGS (10 EXERCISES) ─────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '88888888-8888-8888-8888-888888888801',
    'Romanian Deadlift (RDL)',
    'HAMSTRINGS',
    'Glutes, Lower Back',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-10', '90s',
    'Premier hamstring stretch and hip hinge exercise.',
    '1. Stand tall holding barbell with overhand grip.\n2. Push hips back hinging at waist with soft knee bend.\n3. Lower bar along thighs until hamstring stretch is felt.\n4. Drive hips forward to stand tall.',
    'Keep bar in contact with legs; do not round back.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888802',
    'Lying Leg Curls',
    'HAMSTRINGS',
    'Calves',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    4, '10-12', '60s',
    'Direct hamstring flex isolation.',
    '1. Lie face down on leg curl bench with pad against back of ankles.\n2. Curl pad up towards glutes.\n3. Lower down under control stretch.',
    'Keep hips flat against bench pad.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888803',
    'Seated Leg Curls',
    'HAMSTRINGS',
    'Calves',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    4, '12-15', '60s',
    'High stretch seated hamstring curl.',
    '1. Sit in machine with thigh pad locked down.\n2. Pull heel pad down under seat.\n3. Control return under full stretch.',
    'Emphasizes hamstring stretch under hip flexion.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888804',
    'Single-Leg Dumbbell RDL',
    'HAMSTRINGS',
    'Glutes, Core Balance',
    'Dumbbell',
    'COMPOUND',
    'INTERMEDIATE',
    3, '10-12', '60s',
    'Unilateral hamstring balance.',
    '1. Hold dumbbell in right hand standing on left leg.\n2. Hinge left hip extending right leg back straight.\n3. Return to top.',
    'Keep hips square to ground.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888805',
    'Glute Ham Raise (GHR)',
    'HAMSTRINGS',
    'Glutes, Lower Back',
    'Bodyweight',
    'COMPOUND',
    'PRO',
    3, '6-10', '90s',
    'High intensity hamstring knee flexion and hip extension.',
    '1. Lock feet into GHR bench.\n2. Lower body forward horizontally.\n3. Pull body back up using hamstrings.',
    'Advanced strength requirement.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888806',
    'Barbell Good Mornings',
    'HAMSTRINGS',
    'Lower Back, Glutes',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    3, '10-12', '75s',
    'Posterior chain hip hinge.',
    '1. Rest bar on upper back as in squat.\n2. Hinge forward at hips keeping back flat.\n3. Return to upright stance.',
    'Start with light weight to master hip hinge.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888807',
    'Kettlebell Swings',
    'HAMSTRINGS',
    'Glutes, Core, Cardio',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    4, '15-20', '60s',
    'Explosive hip hinge power.',
    '1. Stand over kettlebell, hike it back between thighs.\n2. Explosively snap hips forward driving kettlebell up to chest height.',
    'Do not lift kettlebell with shoulders; drive with hips.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888808',
    'Cable Pull-Throughs',
    'HAMSTRINGS',
    'Glutes',
    'Cable',
    'COMPOUND',
    'BEGINNER',
    3, '12-15', '60s',
    'Cable hip hinge builder.',
    '1. Stand facing away from low cable rope pulley.\n2. Hinge at hips reaching rope back between legs.\n3. Snap hips forward to stand.',
    'Focus on glute/hamstring squeeze.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888809',
    'Nordic Hamstring Curls',
    'HAMSTRINGS',
    'Calves',
    'Bodyweight',
    'ISOLATION',
    'PRO',
    3, '5-8', '90s',
    'Eccentric hamstring injury prevention exercise.',
    '1. Kneel with ankles anchored securely.\n2. Slowly lower torso forward under eccentric hamstring control.',
    'Land on hands if unable to complete concentric phase.',
    NOW()
),
(
    '88888888-8888-8888-8888-888888888810',
    'Stability Ball Hamstring Rollouts',
    'HAMSTRINGS',
    'Glutes, Core',
    'Bodyweight',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '45s',
    'Core and hamstring curl on ball.',
    '1. Lie on back with heels on Swiss ball.\n2. Bridge hips up and curl ball in towards glutes.\n3. Roll ball back out.',
    'Keep hips elevated.',
    NOW()
);

-- ── GLUTES (10 EXERCISES) ─────────────────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    '99999999-9999-9999-9999-999999999901',
    'Barbell Hip Thrusts',
    'GLUTES',
    'Hamstrings, Quads',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '8-12', '90s',
    'The premier glute max builder.',
    '1. Sit on floor with upper back against flat bench, padded barbell over hips.\n2. Drive heels into floor to extend hips straight up.\n3. Squeeze glutes hard at top lockout for 1-2 seconds.\n4. Lower hips down.',
    'Tuck chin forward slightly to prevent lumbar hyperextension.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999902',
    'Cable Glute Kickbacks',
    'GLUTES',
    'Glute Max',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '45s',
    'Direct cable glute isolation.',
    '1. Attach ankle cuff to low cable.\n2. Kick leg backward driving through heel.\n3. Squeeze glute at top extension.',
    'Keep torso steady.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999903',
    'Glute Bridges (Bodyweight/Weighted)',
    'GLUTES',
    'Hamstrings',
    'Bodyweight',
    'ISOLATION',
    'BEGINNER',
    3, '15-20', '45s',
    'Floor glute activation builder.',
    '1. Lie on back with knees flexed, feet flat.\n2. Raise hips up until alignment from knees to shoulders is straight.\n3. Squeeze glutes.',
    'Drive through heels.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999904',
    'Seated Abductor Machine',
    'GLUTES',
    'Glute Medius & Minimus',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    4, '15-20', '45s',
    'Targets outer glute medius.',
    '1. Sit in hip abductor machine.\n2. Push pads outward spreading legs apart.\n3. Pause 1 second, control return.',
    'Lean slightly forward for extra glute focus.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999905',
    'Sumo Barbell Deadlift',
    'GLUTES',
    'Quads, Adductors',
    'Barbell',
    'COMPOUND',
    'INTERMEDIATE',
    4, '5-8', '120s',
    'Wide stance deadlift loading glutes and inner thighs.',
    '1. Stand with wide stance, toes pointed outwards at 45 degrees.\n2. Grip bar inside knees, drive floor away standing tall.',
    'Keep knees tracking inline with toes.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999906',
    'Step-Ups (Glute Bias)',
    'GLUTES',
    'Quads',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    3, '10-12', '60s',
    'Hinge forward step-up targeting glutes.',
    '1. Step foot on box, tilt torso slightly forward at 30 degrees.\n2. Drive through heel to stand tall on box.',
    'Avoid pushing off lower foot.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999907',
    'Frog Pumps',
    'GLUTES',
    'Glute Max',
    'Bodyweight',
    'ISOLATION',
    'BEGINNER',
    3, '20-30', '30s',
    'High-rep glute burnout.',
    '1. Lie on back, place soles of feet together with knees bent out wide.\n2. Pump hips up off floor squeezing glutes.',
    'High rep pump exercise.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999908',
    'Reverse Hyperextension',
    'GLUTES',
    'Lower Back, Hamstrings',
    'Machine',
    'COMPOUND',
    'INTERMEDIATE',
    3, '12-15', '60s',
    'Decompresses spine while strengthening glutes.',
    '1. Rest torso on bench with legs hanging free.\n2. Lift legs straight up behind body squeezing glutes.',
    'Smooth arc movement.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999909',
    'Cable Standing Side Abduction',
    'GLUTES',
    'Glute Medius',
    'Cable',
    'ISOLATION',
    'BEGINNER',
    3, '12-15', '45s',
    'Lateral hip raise.',
    '1. Attach ankle cuff to low cable.\n2. Raise leg out to side in controlled motion.',
    'Keep torso upright.',
    NOW()
),
(
    '99999999-9999-9999-9999-999999999910',
    'Curtsy Dumbbell Lunges',
    'GLUTES',
    'Quads, Glute Medius',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    3, '10-12', '60s',
    'Cross-behind lunge targeting glute medius.',
    '1. Hold dumbbells at sides.\n2. Step left foot back behind right foot in curtsy lunge.\n3. Return to top.',
    'Keep front knee stable.',
    NOW()
);

-- ── CALVES & FOREARMS (10 EXERCISES) ──────────────────────────────────────
INSERT INTO exercises (id, name, muscle_group, secondary_muscles, equipment, mechanics, difficulty_level, recommended_sets, recommended_reps, rest_interval, description, execution_steps, safety_tips, created_at)
VALUES
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01',
    'Standing Barbell Calf Raises',
    'CALVES',
    'Gastrocnemius',
    'Barbell',
    'ISOLATION',
    'BEGINNER',
    4, '15-20', '45s',
    'Builds calf height and gastrocnemius size.',
    '1. Stand on raised calf block with bar on shoulders.\n2. Lower heels down for deep stretch.\n3. Press up onto toes squeezing calves at top.',
    'Pause 1 second at top and bottom of each rep.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02',
    'Seated Calf Raise Machine',
    'CALVES',
    'Soleus Muscle',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    4, '15-20', '45s',
    'Isolates soleus calf head under bent knee.',
    '1. Sit in machine with thigh pad locked.\n2. Drop heels down deep.\n3. Drive up onto toes.',
    'Emphasizes soleus muscle.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03',
    'Donkey Calf Raises',
    'CALVES',
    'Gastrocnemius',
    'Machine',
    'ISOLATION',
    'INTERMEDIATE',
    3, '15-20', '45s',
    'Deep stretch calf builder.',
    '1. Hinge at waist on calf machine with hips supported.\n2. Extend toes up and down under full stretch.',
    'Full stretch at bottom.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa04',
    'Leg Press Calf Raises',
    'CALVES',
    'Gastrocnemius',
    'Machine',
    'ISOLATION',
    'BEGINNER',
    3, '15-20', '45s',
    'Heavy calf loading on leg press sled.',
    '1. Place balls of feet on bottom edge of leg press sled.\n2. Flex toes forward extending calves.',
    'Do not let feet slip off edge.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa05',
    'Single-Leg Dumbbell Calf Raise',
    'CALVES',
    'Gastrocnemius, Balance',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    3, '15-20', '30s',
    'Unilateral calf stretch.',
    '1. Hold dumbbell in one hand, stand on single foot on step edge.\n2. Raise up onto toes.',
    'Unilateral equal development.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa06',
    'Barbell Wrist Curls',
    'FOREARMS',
    'Wrist Flexors',
    'Barbell',
    'ISOLATION',
    'BEGINNER',
    4, '15-20', '45s',
    'Builds inner forearm flexor mass.',
    '1. Rest forearms on bench holding barbell palms up.\n2. Curl wrist upward squeezing forearms.',
    'Keep forearms flat on pad.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa07',
    'Reverse Barbell Wrist Curls',
    'FOREARMS',
    'Wrist Extensors',
    'Barbell',
    'ISOLATION',
    'BEGINNER',
    4, '15-20', '45s',
    'Builds top forearm extensor muscles.',
    '1. Rest forearms on bench palms facing down holding barbell.\n2. Curl wrists upward.',
    'Builds top forearm thickness.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa08',
    'Farmers Walk Heavy Hold',
    'FOREARMS',
    'Grip, Traps, Core',
    'Dumbbell',
    'COMPOUND',
    'BEGINNER',
    4, '45s Carry', '60s',
    'Grip strength and forearm endurance.',
    '1. Pick up heavy dumbbells.\n2. Walk tall with chest open for distance/time.',
    'Do not let shoulders slump.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa09',
    'Plate Pinch Hold',
    'FOREARMS',
    'Pinch Grip',
    'Dumbbell',
    'ISOLATION',
    'BEGINNER',
    3, '30s Hold', '45s',
    'Hand pinch grip builder.',
    '1. Pinch two smooth weight plates together between thumb and fingers.\n2. Hold timed for duration.',
    'Tests hand pinch strength.',
    NOW()
),
(
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10',
    'Reverse Grip EZ-Bar Curls',
    'FOREARMS',
    'Brachioradialis & Biceps',
    'Barbell',
    'COMPOUND',
    'BEGINNER',
    3, '10-12', '60s',
    'Top arm and forearm builder.',
    '1. Hold EZ-bar with overhand (pronated) grip.\n2. Curl bar up towards shoulders.',
    'Targets brachioradialis.',
    NOW()
);
