-- V37: Add micronutrient and recipe columns to food table
ALTER TABLE food ADD COLUMN IF NOT EXISTS magnesium DOUBLE PRECISION;
ALTER TABLE food ADD COLUMN IF NOT EXISTS potassium DOUBLE PRECISION;
ALTER TABLE food ADD COLUMN IF NOT EXISTS vitamin_c DOUBLE PRECISION;
ALTER TABLE food ADD COLUMN IF NOT EXISTS vitamin_d DOUBLE PRECISION;
ALTER TABLE food ADD COLUMN IF NOT EXISTS is_recipe BOOLEAN DEFAULT FALSE;
ALTER TABLE food ADD COLUMN IF NOT EXISTS recipe_ingredients TEXT;
ALTER TABLE food ADD COLUMN IF NOT EXISTS recipe_instructions TEXT;
ALTER TABLE food ADD COLUMN IF NOT EXISTS magnesium_rich BOOLEAN DEFAULT FALSE;
