-- V41: Update recipe nutritional data from db-recipes.json (only records with calories > 0)
-- Updates calories, protein, carbs, fat, fiber for recipes imported in V39

UPDATE food SET calories = 2565, protein = 200, carbohydrates = 76, fat = 159, fiber = 4, cooking_time = 15 WHERE description = 'Baked Shrimp Scampi' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3057, protein = 42, carbohydrates = 78, fat = 297, fiber = 23, cooking_time = 15 WHERE description = 'Greek Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2883, protein = 227, carbohydrates = 120, fat = 164, fiber = 15, cooking_time = 15 WHERE description = 'Margherita Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1335, protein = 35, carbohydrates = 172, fat = 62, fiber = 37, cooking_time = 15 WHERE description = 'Mexican Ensalada' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1552, protein = 24, carbohydrates = 72, fat = 120, fiber = 64, cooking_time = 15 WHERE description = 'Guacamole' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 684, protein = 24, carbohydrates = 73, fat = 35, fiber = 20, cooking_time = 15 WHERE description = 'Super Protein Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 639, protein = 38, carbohydrates = 81, fat = 22, fiber = 18, cooking_time = 15 WHERE description = 'The Shake' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 558, protein = 13, carbohydrates = 40, fat = 44, fiber = 0, cooking_time = 15 WHERE description = 'Extreme Green Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 559, protein = 12, carbohydrates = 30, fat = 21, fiber = 5, cooking_time = 15 WHERE description = 'Popeye''s Muscle Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 282, protein = 17, carbohydrates = 13, fat = 18, fiber = 4, cooking_time = 15 WHERE description = 'Breakfast Mediterranean Scramble' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 376, protein = 11, carbohydrates = 57, fat = 14, fiber = 9, cooking_time = 15 WHERE description = 'Best Oatmeal Ever' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3610, protein = 64, carbohydrates = 468, fat = 179, fiber = 41, cooking_time = 15 WHERE description = 'The Original Chex Party Mix' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 961, protein = 35, carbohydrates = 157, fat = 20, fiber = 6, cooking_time = 15 WHERE description = 'Handmade Pasta' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 184, protein = 8, carbohydrates = 39, fat = 4, fiber = 15, cooking_time = 15 WHERE description = 'Emeril Essence Creole Seasoning' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1560, protein = 72, carbohydrates = 248, fat = 40, fiber = 80, cooking_time = 15 WHERE description = 'Vegetarian Chili' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 489, protein = 2, carbohydrates = 16, fat = 51, fiber = 4, cooking_time = 15 WHERE description = 'Basil-Lime Vinaigrette' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2259, protein = 159, carbohydrates = 304, fat = 43, fiber = 144, cooking_time = 15 WHERE description = 'Lentil Soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 168, protein = 0, carbohydrates = 44, fat = 0, fiber = 0, cooking_time = 15 WHERE description = 'Natural sports drink' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 216, protein = 6, carbohydrates = 50, fat = 1, fiber = 10, cooking_time = 15 WHERE description = 'Vegetable Stock' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1294, protein = 44, carbohydrates = 186, fat = 46, fiber = 14, cooking_time = 600 WHERE description = 'Spicy Rice Casserole' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3379, protein = 81, carbohydrates = 303, fat = 221, fiber = 58, cooking_time = 15 WHERE description = 'Citrus Rice Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2338, protein = 88, carbohydrates = 276, fat = 112, fiber = 20, cooking_time = 900 WHERE description = 'Straw and Hay Fettuccine Tangle' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 770, protein = 40, carbohydrates = 82, fat = 32, fiber = 14, cooking_time = 15 WHERE description = 'Green-packed Stir Fry with Fresh Herbs' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1104, protein = 16, carbohydrates = 72, fat = 86, fiber = 6, cooking_time = 15 WHERE description = 'Almond Caesar salad with croutons' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1199, protein = 43, carbohydrates = 144, fat = 51, fiber = 22, cooking_time = 300 WHERE description = 'Black bean and cheese tacos' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2348, protein = 59, carbohydrates = 227, fat = 144, fiber = 20, cooking_time = 15 WHERE description = 'Joan''s Broccoli Madness' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 892, protein = 8, carbohydrates = 32, fat = 84, fiber = 4, cooking_time = 15 WHERE description = 'Creamy tomato soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1848, protein = 100, carbohydrates = 132, fat = 104, fiber = 8, cooking_time = 600 WHERE description = 'Triple Grilled Cheese' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1928, protein = 156, carbohydrates = 292, fat = 24, fiber = 12, cooking_time = 15 WHERE description = 'Soba salad with asparagus and shrimp' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1590, protein = 76, carbohydrates = 296, fat = 28, fiber = 40, cooking_time = 15 WHERE description = 'Tofu and Sweet Potato Jambalaya' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1508, protein = 48, carbohydrates = 166, fat = 70, fiber = 8, cooking_time = 900 WHERE description = 'Wild Mushroom Risotto' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 996, protein = 36, carbohydrates = 138, fat = 60, fiber = 10, cooking_time = 15 WHERE description = 'Brown rice, chickpea, feta, and mint salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 900, protein = 44, carbohydrates = 22, fat = 78, fiber = 6, cooking_time = 15 WHERE description = 'Spinach souffle' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1908, protein = 40, carbohydrates = 200, fat = 80, fiber = 12, cooking_time = 900 WHERE description = 'Peanut Noodle Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1968, protein = 104, carbohydrates = 212, fat = 96, fiber = 8, cooking_time = 15 WHERE description = 'Pizza bianca' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2136, protein = 42, carbohydrates = 294, fat = 102, fiber = 6, cooking_time = 15 WHERE description = 'Cherry-lime cups' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1388, protein = 152, carbohydrates = 120, fat = 28, fiber = 20, cooking_time = 1800 WHERE description = 'Shrimp and edamame with lime' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1680, protein = 36, carbohydrates = 288, fat = 60, fiber = 24, cooking_time = 1500 WHERE description = 'Strawberries and cream bars' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1188, protein = 36, carbohydrates = 160, fat = 52, fiber = 12, cooking_time = 1500 WHERE description = 'Frozen chocolate mousse trifles' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1732, protein = 56, carbohydrates = 196, fat = 100, fiber = 0, cooking_time = 1500 WHERE description = 'Frozen lemon souffle' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3684, protein = 48, carbohydrates = 288, fat = 276, fiber = 12, cooking_time = 1800 WHERE description = 'Coconut lime semifreddo' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1320, protein = 12, carbohydrates = 276, fat = 0, fiber = 24, cooking_time = 600 WHERE description = 'Sweet cherry granita' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2168, protein = 84, carbohydrates = 264, fat = 88, fiber = 44, cooking_time = 15 WHERE description = 'Tex-mex rice and black eyed peas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2236, protein = 116, carbohydrates = 268, fat = 80, fiber = 48, cooking_time = 15 WHERE description = 'Baked eggs and beans on toast' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1720, protein = 116, carbohydrates = 94, fat = 96, fiber = 12, cooking_time = 900 WHERE description = 'Warm shrimp and potato salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 408, protein = 12, carbohydrates = 72, fat = 18, fiber = 12, cooking_time = 300 WHERE description = 'Spicy sauteed kale with lemon' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 140, protein = 2, carbohydrates = 32, fat = 0, fiber = 8, cooking_time = 15 WHERE description = 'Asian Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1168, protein = 96, carbohydrates = 128, fat = 48, fiber = 40, cooking_time = 15 WHERE description = 'Broccoli soup with cheddar toasts' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2362, protein = 72, carbohydrates = 300, fat = 113, fiber = 14, cooking_time = 1200 WHERE description = 'Dang cold Asian noodle salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1048, protein = 128, carbohydrates = 40, fat = 40, fiber = 8, cooking_time = 600 WHERE description = 'Shrimp and cabbage stir fry' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3060, protein = 96, carbohydrates = 348, fat = 120, fiber = 36, cooking_time = 15 WHERE description = 'Orecchiette with roasted cauliflower' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1440, protein = 64, carbohydrates = 208, fat = 44, fiber = 72, cooking_time = 1800 WHERE description = 'Black bean salad with chipotle honey dressing' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1976, protein = 84, carbohydrates = 272, fat = 64, fiber = 20, cooking_time = 600 WHERE description = 'Pasta with asparagus and egg' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3104, protein = 88, carbohydrates = 328, fat = 168, fiber = 40, cooking_time = 2400 WHERE description = 'Spanakopita' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3600, protein = 50, carbohydrates = 550, fat = 160, fiber = 20, cooking_time = 1200 WHERE description = 'Simple lemon cake' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 6012, protein = 90, carbohydrates = 720, fat = 342, fiber = 54, cooking_time = 900 WHERE description = 'Gooey layered everything bars' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 168, protein = 12, carbohydrates = 44, fat = 0, fiber = 20, cooking_time = 600 WHERE description = 'Chili Lemon Cauliflower' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2700, protein = 60, carbohydrates = 300, fat = 160, fiber = 40, cooking_time = 600 WHERE description = 'Pecan molasses granola' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2224, protein = 172, carbohydrates = 106, fat = 123, fiber = 25, cooking_time = 900 WHERE description = 'Salmon and potatoes in tomato sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1320, protein = 72, carbohydrates = 128, fat = 64, fiber = 16, cooking_time = 900 WHERE description = 'Marinated feta, spinach & poached egg salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1640, protein = 72, carbohydrates = 172, fat = 72, fiber = 28, cooking_time = 1200 WHERE description = 'Smoky white bean and arugula panini' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2736, protein = 66, carbohydrates = 432, fat = 102, fiber = 66, cooking_time = 1200 WHERE description = 'Easy chickpea and vegetable curry' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3140, protein = 20, carbohydrates = 180, fat = 270, fiber = 0, cooking_time = 1500 WHERE description = 'Maple brown butter semifreddo' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3384, protein = 56, carbohydrates = 376, fat = 192, fiber = 8, cooking_time = 1500 WHERE description = 'Brown sugar buttermilk pie' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1656, protein = 106, carbohydrates = 233, fat = 33, fiber = 45, cooking_time = 15 WHERE description = 'Mushroom and lentil soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1764, protein = 68, carbohydrates = 268, fat = 44, fiber = 40, cooking_time = 900 WHERE description = 'Indian Chickpea Wrap' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2060, protein = 62, carbohydrates = 69, fat = 182, fiber = 13, cooking_time = 15 WHERE description = 'Kale and feta salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1780, protein = 72, carbohydrates = 96, fat = 118, fiber = 17, cooking_time = 900 WHERE description = 'Antipasto Chef''s Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 800, protein = 42, carbohydrates = 123, fat = 22, fiber = 22, cooking_time = 15 WHERE description = 'Moroccan lentil salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1240, protein = 39, carbohydrates = 156, fat = 59, fiber = 26, cooking_time = 15 WHERE description = 'Tuscan panzanella salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 70, protein = 6, carbohydrates = 0, fat = 5, fiber = 0, cooking_time = 15 WHERE description = 'Eggs' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3024, protein = 183, carbohydrates = 163, fat = 182, fiber = 13, cooking_time = 15 WHERE description = 'Salmon Tuscano with Herbed Orzo' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 500, protein = 30, carbohydrates = 68, fat = 14, fiber = 10, cooking_time = 600 WHERE description = 'Tomato-Basil Soup with Ricotta Dumplings' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1136, protein = 44, carbohydrates = 76, fat = 68, fiber = 16, cooking_time = 600 WHERE description = 'Tomato, Basil and Portobello Napoleons' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2800, protein = 88, carbohydrates = 296, fat = 136, fiber = 32, cooking_time = 15 WHERE description = 'Creamy Broccoli & Sun-Dried Tomato Orzotto' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3431, protein = 142, carbohydrates = 582, fat = 58, fiber = 54, cooking_time = 900 WHERE description = 'Gnocchi' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 4300, protein = 15, carbohydrates = 520, fat = 180, fiber = 3, cooking_time = 15 WHERE description = 'Grilled Cheese & Tomato Skillet' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2100, protein = 0, carbohydrates = 0, fat = 114, fiber = 30, cooking_time = 15 WHERE description = 'Mediterranean Patio Pizza' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3340, protein = 203, carbohydrates = 328, fat = 146, fiber = 41, cooking_time = 15 WHERE description = 'Baked Ziti with Crunchy Italian Salad and Garlic Bread' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1254, protein = 36, carbohydrates = 156, fat = 48, fiber = 30, cooking_time = 1200 WHERE description = 'All-day minestrone (slow cooker)' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 275, protein = 23, carbohydrates = 34, fat = 7, fiber = 4, cooking_time = 15 WHERE description = 'Berry Granola Parfait' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1751, protein = 59, carbohydrates = 238, fat = 66, fiber = 36, cooking_time = 900 WHERE description = 'Smoked salmon baked potatoes' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1504, protein = 44, carbohydrates = 292, fat = 20, fiber = 36, cooking_time = 900 WHERE description = 'Samosa baked potatoes' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1428, protein = 60, carbohydrates = 136, fat = 80, fiber = 20, cooking_time = 900 WHERE description = 'Apple-cheddar baked sweet potatoes' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2240, protein = 64, carbohydrates = 304, fat = 72, fiber = 32, cooking_time = 900 WHERE description = 'Paella pasta salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2358, protein = 84, carbohydrates = 372, fat = 60, fiber = 36, cooking_time = 600 WHERE description = 'Pinto bean and poblano tacos' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1964, protein = 96, carbohydrates = 200, fat = 88, fiber = 28, cooking_time = 2100 WHERE description = 'Tofu Parmesan' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2272, protein = 84, carbohydrates = 284, fat = 92, fiber = 12, cooking_time = 1500 WHERE description = 'Pasta with escarole' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1988, protein = 96, carbohydrates = 280, fat = 60, fiber = 44, cooking_time = 1200 WHERE description = 'Squash and bean burritos' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1716, protein = 168, carbohydrates = 72, fat = 80, fiber = 20, cooking_time = 600 WHERE description = 'Broiled halibut with ricotta-pea puree' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1365, protein = 35, carbohydrates = 210, fat = 48, fiber = 16, cooking_time = 1200 WHERE description = 'Veggie Carribean Panini' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3108, protein = 124, carbohydrates = 264, fat = 180, fiber = 36, cooking_time = 600 WHERE description = 'Baja fish tacos' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 436, protein = 24, carbohydrates = 30, fat = 26, fiber = 4, cooking_time = 300 WHERE description = 'Open face egg and tomato sandwich' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1252, protein = 76, carbohydrates = 196, fat = 20, fiber = 52, cooking_time = 1200 WHERE description = 'Black bean and brown rice cakes' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 339, protein = 16, carbohydrates = 38, fat = 15, fiber = 7, cooking_time = 300 WHERE description = 'English muffin with apple and cheddar' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2596, protein = 60, carbohydrates = 104, fat = 168, fiber = 32, cooking_time = 900 WHERE description = 'Couscous stuffed bellpeppers with basil sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 397, protein = 11, carbohydrates = 17, fat = 33, fiber = 9, cooking_time = 1500 WHERE description = 'Salad with egg, nuts, and veggies' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3204, protein = 182, carbohydrates = 486, fat = 80, fiber = 136, cooking_time = 1200 WHERE description = 'Pesto millet grits with tomato ragout' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1428, protein = 116, carbohydrates = 156, fat = 36, fiber = 8, cooking_time = 1200 WHERE description = 'Coconut shrimp with tropical rice' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1808, protein = 96, carbohydrates = 184, fat = 76, fiber = 32, cooking_time = 1200 WHERE description = 'Shakshuka with chickpeas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 308, protein = 10, carbohydrates = 33, fat = 16, fiber = 4, cooking_time = 300 WHERE description = 'Mediterranean Grain Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1772, protein = 72, carbohydrates = 236, fat = 64, fiber = 12, cooking_time = 1800 WHERE description = 'Vegetable and tofu pad thai' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1032, protein = 112, carbohydrates = 36, fat = 40, fiber = 4, cooking_time = 900 WHERE description = 'Wasabi Salmon with Miso-Sesame Sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 408, protein = 18, carbohydrates = 42, fat = 18, fiber = 4, cooking_time = 300 WHERE description = 'Egg sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1880, protein = 64, carbohydrates = 252, fat = 72, fiber = 28, cooking_time = 900 WHERE description = 'Black-eyed pea burgers with summer squash slaw' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1920, protein = 64, carbohydrates = 284, fat = 68, fiber = 20, cooking_time = 900 WHERE description = 'Korean scallion pancakes with vegetable salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1736, protein = 24, carbohydrates = 88, fat = 160, fiber = 24, cooking_time = 300 WHERE description = 'Sweet, Spicy & Salty Candied Pecans' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1360, protein = 64, carbohydrates = 120, fat = 80, fiber = 36, cooking_time = 1200 WHERE description = 'Panko-crusted tofu with black bean salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2280, protein = 84, carbohydrates = 288, fat = 90, fiber = 48, cooking_time = 900 WHERE description = 'Farro Fagioli Minestrone' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1560, protein = 72, carbohydrates = 132, fat = 90, fiber = 24, cooking_time = 600 WHERE description = 'Spanish frittata with mixed greens salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2280, protein = 84, carbohydrates = 294, fat = 90, fiber = 30, cooking_time = 1500 WHERE description = 'Roasted root vegetables with creamy grits' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1920, protein = 60, carbohydrates = 234, fat = 90, fiber = 36, cooking_time = 1800 WHERE description = 'Farmer''s market vegetable pot pie' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1620, protein = 78, carbohydrates = 204, fat = 60, fiber = 36, cooking_time = 600 WHERE description = 'Barley risotto verde' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2280, protein = 84, carbohydrates = 216, fat = 120, fiber = 24, cooking_time = 1200 WHERE description = 'French onion potato tart' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 70, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 300 WHERE description = 'Perfect soft cooked egg' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 7792, protein = 368, carbohydrates = 576, fat = 448, fiber = 72, cooking_time = 3000 WHERE description = 'Wild mushroom and cauliflower lasagna' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 296, protein = 12, carbohydrates = 52, fat = 6, fiber = 3, cooking_time = 300 WHERE description = 'Hot cereal with apple butter and walnuts' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1176, protein = 64, carbohydrates = 44, fat = 84, fiber = 4, cooking_time = 1200 WHERE description = 'Mexican potato omelet' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2664, protein = 30, carbohydrates = 150, fat = 222, fiber = 30, cooking_time = 1200 WHERE description = 'Gazpacho Soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1576, protein = 100, carbohydrates = 152, fat = 72, fiber = 28, cooking_time = 900 WHERE description = 'Eggs with mushrooms and tomatoes' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 383, protein = 12, carbohydrates = 24, fat = 29, fiber = 5, cooking_time = 300 WHERE description = 'Fruit and cheese breakfast' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 708, protein = 30, carbohydrates = 60, fat = 38, fiber = 10, cooking_time = 300 WHERE description = 'Mustard, Avocado, and Dill on a Whole-Wheat Muffin With Boiled Egg' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 264, protein = 13, carbohydrates = 28, fat = 11, fiber = 3, cooking_time = 300 WHERE description = 'Savory Oatmeal and Soft-Cooked Egg' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 384, protein = 11, carbohydrates = 32, fat = 24, fiber = 3, cooking_time = 300 WHERE description = 'Adult Lunchable with Veggies, Egg, and Boursin' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 504, protein = 24, carbohydrates = 85, fat = 17, fiber = 7, cooking_time = 1200 WHERE description = 'Seitan and three-color pepper stir-fry bento' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1800, protein = 48, carbohydrates = 396, fat = 0, fiber = 0, cooking_time = 1200 WHERE description = 'The best angel food cake' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 408, protein = 8, carbohydrates = 64, fat = 16, fiber = 16, cooking_time = 15 WHERE description = 'Carrot and celeriac (celery root) salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 958, protein = 36, carbohydrates = 166, fat = 26, fiber = 16, cooking_time = 15 WHERE description = 'Spring Chickpea Pasta Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 208, protein = 4, carbohydrates = 12, fat = 16, fiber = 4, cooking_time = 900 WHERE description = 'Carrot kinpira' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 372, protein = 4, carbohydrates = 28, fat = 28, fiber = 12, cooking_time = 600 WHERE description = 'Salt block cucumber salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2968, protein = 56, carbohydrates = 248, fat = 200, fiber = 16, cooking_time = 900 WHERE description = 'Salt-baked walnut brioche scones' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 453, protein = 20, carbohydrates = 51, fat = 20, fiber = 6, cooking_time = 900 WHERE description = 'Basic bento: tofu and egg' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2460, protein = 204, carbohydrates = 36, fat = 156, fiber = 12, cooking_time = 900 WHERE description = 'Petite vegetable frittatas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 720, protein = 54, carbohydrates = 34, fat = 36, fiber = 8, cooking_time = 600 WHERE description = 'Roasted Shrimp, Endive, and Red Onion Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1220, protein = 40, carbohydrates = 138, fat = 60, fiber = 12, cooking_time = 900 WHERE description = 'Udon noodle soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1580, protein = 56, carbohydrates = 228, fat = 55, fiber = 20, cooking_time = 900 WHERE description = 'Oaxaca Cheese & Plantain Tortas with Tangelo & Radish Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1280, protein = 34, carbohydrates = 138, fat = 72, fiber = 22, cooking_time = 900 WHERE description = 'Mushroom & Broccoli Casserole with Baked Pastry' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1500, protein = 56, carbohydrates = 234, fat = 40, fiber = 24, cooking_time = 600 WHERE description = 'Penne & Arrabbiata Sauce with Roasted Carrot & Tangelo Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1340, protein = 68, carbohydrates = 138, fat = 62, fiber = 16, cooking_time = 900 WHERE description = 'Smoky Seared Cod with Roasted Potatoes & Dates' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1170, protein = 58, carbohydrates = 100, fat = 58, fiber = 18, cooking_time = 900 WHERE description = 'Kale & White Cheddar Quesadillas with Radishes & Fried Eggs' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2508, protein = 136, carbohydrates = 200, fat = 128, fiber = 32, cooking_time = 1800 WHERE description = 'Baked Tofu Banh Mi Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 854, protein = 44, carbohydrates = 32, fat = 62, fiber = 12, cooking_time = 600 WHERE description = 'Mexican caprese salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 270, protein = 7, carbohydrates = 44, fat = 9, fiber = 6, cooking_time = 300 WHERE description = 'Chocolate covered strawberry quick oatmeal' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 424, protein = 28, carbohydrates = 40, fat = 24, fiber = 16, cooking_time = 900 WHERE description = 'Golden-crusted Brussels sprouts' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1560, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 15 WHERE description = 'Sweet and Spicy Tofu with Jasmine Rice and Crispy Shallot' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1180, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 1200 WHERE description = 'Olive and Pepper Grilled Cheese Sandwiches' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2444, protein = 100, carbohydrates = 352, fat = 92, fiber = 20, cooking_time = 1800 WHERE description = 'Tofu katsu onigirazu' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 338, protein = 8, carbohydrates = 53, fat = 12, fiber = 9, cooking_time = 1200 WHERE description = 'Super veggie onigirazu' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2352, protein = 112, carbohydrates = 112, fat = 160, fiber = 16, cooking_time = 600 WHERE description = 'Oregano halloumi with orzo salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1200, protein = 36, carbohydrates = 194, fat = 64, fiber = 24, cooking_time = 900 WHERE description = 'Cucumber, Avocado, and Miso Spinach Rice Bowl' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1600, protein = 56, carbohydrates = 156, fat = 76, fiber = 26, cooking_time = 900 WHERE description = 'Spicy poblano pepper and cheese tortas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1340, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 900 WHERE description = 'Chirashi-Style Rice Bowls' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1580, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 15 WHERE description = 'Sweet & Savory Korean Rice Cakes' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 243, protein = 13, carbohydrates = 5, fat = 19, fiber = 2, cooking_time = 300 WHERE description = 'Salsa Scramble' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 332, protein = 21, carbohydrates = 4, fat = 26, fiber = 1, cooking_time = 300 WHERE description = 'Cheesy mushroom omelette' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 536, protein = 22, carbohydrates = 222, fat = 46, fiber = 10, cooking_time = 600 WHERE description = 'Black Forest Bircher (overnight oats)' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 327, protein = 12, carbohydrates = 23, fat = 23, fiber = 11, cooking_time = 180 WHERE description = 'Almond muffin in a minute' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1278, protein = 39, carbohydrates = 148, fat = 60, fiber = 5, cooking_time = 300 WHERE description = 'Pesto Cavatelli w/ Mushrooms and Spicy Breadcrumbs' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 702, protein = 30, carbohydrates = 120, fat = 18, fiber = 30, cooking_time = 900 WHERE description = 'Black bean mini burgers' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 348, protein = 9, carbohydrates = 62, fat = 7, fiber = 2, cooking_time = 15 WHERE description = 'Mini hamburger bento (Select a mini burger recipe too)' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 192, protein = 18, carbohydrates = 4, fat = 11, fiber = 0, cooking_time = 900 WHERE description = 'Fresh salmon mini burgers' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 387, protein = 11, carbohydrates = 22, fat = 29, fiber = 6, cooking_time = 300 WHERE description = 'Avocado, olive tapenade, and chedder toast' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 714, protein = 36, carbohydrates = 92, fat = 28, fiber = 22, cooking_time = 300 WHERE description = 'Cozy bean and egg skillet for two' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 436, protein = 16, carbohydrates = 28, fat = 28, fiber = 2, cooking_time = 300 WHERE description = 'Whipped eggs on toast' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1241, protein = 54, carbohydrates = 96, fat = 69, fiber = 11, cooking_time = 900 WHERE description = 'Peach & Pickled Pepper Grilled Cheese' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1379, protein = 51, carbohydrates = 170, fat = 45, fiber = 17, cooking_time = 2100 WHERE description = 'Black bean and zucchini enchiladas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1540, protein = 36, carbohydrates = 174, fat = 82, fiber = 16, cooking_time = 600 WHERE description = 'Banh Mi Sandwiches with Roasted Broccoli' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1333, protein = 46, carbohydrates = 158, fat = 54, fiber = 14, cooking_time = 600 WHERE description = 'Roasted Sweet Potato Quesadillas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3648, protein = 156, carbohydrates = 282, fat = 216, fiber = 12, cooking_time = 15 WHERE description = 'Baked macaroni and cheese' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1662, protein = 44, carbohydrates = 162, fat = 100, fiber = 18, cooking_time = 1200 WHERE description = 'Cavatelli and kale with fried rosemary and walnuts' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2350, protein = 95, carbohydrates = 184, fat = 141, fiber = 47, cooking_time = 1800 WHERE description = 'Falafel with Spicy Feta Sauce and Vegetable Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1520, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 1800 WHERE description = 'Pickled Beet & Hard-Boiled Egg Sandwiches with Smoky Mayonnaise' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3200, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 3300 WHERE description = 'Butternut Squash & Fontina Calzones with Apple & Arugula Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1086, protein = 39, carbohydrates = 96, fat = 61, fiber = 9, cooking_time = 1500 WHERE description = 'Egg, cucumber, and smoked gouda spread sandwiches' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1454, protein = 55, carbohydrates = 160, fat = 68, fiber = 20, cooking_time = 2100 WHERE description = 'Indian-style paneer and creamy tomato curry' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1480, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 600 WHERE description = 'Smoky Brussels Sprouts & Black Bean Tacos' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1631, protein = 96, carbohydrates = 120, fat = 82, fiber = 6, cooking_time = 600 WHERE description = 'Japanese egg salad sandwich (tamago sando)' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1520, protein = 28, carbohydrates = 154, fat = 84, fiber = 10, cooking_time = 600 WHERE description = 'Scallops over Truffled Mushroom Risotto' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 441, protein = 15, carbohydrates = 76, fat = 10, fiber = 13, cooking_time = 300 WHERE description = 'Dark chocolate raspberry breakfast bake' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 475, protein = 14, carbohydrates = 56, fat = 23, fiber = 8, cooking_time = 300 WHERE description = 'Oatmeal cookie dough breakfast bake' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1483, protein = 68, carbohydrates = 268, fat = 61, fiber = 26, cooking_time = 2400 WHERE description = 'Broccoli and Mozzarella Pizza' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1204, protein = 57, carbohydrates = 107, fat = 51, fiber = 26, cooking_time = 2100 WHERE description = 'Roasted broccoli and fregola sarda pasta' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 189, protein = 5, carbohydrates = 29, fat = 6, fiber = 1, cooking_time = 15 WHERE description = 'Single Serve Mug Coffee Cake' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1528, protein = 60, carbohydrates = 161, fat = 74, fiber = 14, cooking_time = 15 WHERE description = 'Mediterranean egg salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1935, protein = 61, carbohydrates = 214, fat = 92, fiber = 17, cooking_time = 900 WHERE description = 'Mediterranean pasta salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1524, protein = 33, carbohydrates = 119, fat = 103, fiber = 23, cooking_time = 15 WHERE description = 'Boursin broccoli soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1809, protein = 43, carbohydrates = 201, fat = 84, fiber = 17, cooking_time = 15 WHERE description = 'Broccoli rice casserole' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 668, protein = 25, carbohydrates = 53, fat = 42, fiber = 23, cooking_time = 15 WHERE description = 'Overnight Chia Pudding' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1186, protein = 32, carbohydrates = 162, fat = 48, fiber = 8, cooking_time = 15 WHERE description = 'Creamy Summer Veggie Risotto' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1040, protein = 44, carbohydrates = 82, fat = 62, fiber = 16, cooking_time = 900 WHERE description = 'Potato and kale hash with baked eggs and hot sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 298, protein = 11, carbohydrates = 38, fat = 10, fiber = 1, cooking_time = 600 WHERE description = 'Goat Cheese Sandwich with Arugula & Cucumber' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1139, protein = 40, carbohydrates = 126, fat = 51, fiber = 9, cooking_time = 300 WHERE description = 'Cheesy portobello mushroom caps' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2243, protein = 42, carbohydrates = 253, fat = 58, fiber = 40, cooking_time = 900 WHERE description = 'Sweet Potato Bowl with Creamy Tahini Dressing' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1193, protein = 35, carbohydrates = 164, fat = 50, fiber = 19, cooking_time = 600 WHERE description = 'Italian garden veggie soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3520, protein = 64, carbohydrates = 576, fat = 112, fiber = 16, cooking_time = 1800 WHERE description = 'Perfectly Pillowly Cinnamon Rolls' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 3344, protein = 80, carbohydrates = 336, fat = 192, fiber = 16, cooking_time = 600 WHERE description = 'Vegetable Tortilla Roll-ups' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1470, protein = 38, carbohydrates = 130, fat = 46, fiber = 20, cooking_time = 600 WHERE description = 'Crunchy chickpea pita pockets' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 504, protein = 19, carbohydrates = 38, fat = 33, fiber = 0, cooking_time = 15 WHERE description = 'Cheese Board Bento' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1180, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 1200 WHERE description = 'Vegetable Fried Rice with Broccoli, Carrots, & Spicy Pepper Sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1044, protein = 62, carbohydrates = 98, fat = 48, fiber = 8, cooking_time = 600 WHERE description = 'Seared tilapia and lemon-caper sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 426, protein = 30, carbohydrates = 48, fat = 11, fiber = 1, cooking_time = 1200 WHERE description = 'Gyoza bento' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 430, protein = 31, carbohydrates = 53, fat = 14, fiber = 16, cooking_time = 15 WHERE description = 'Pan fried tofu and soba noodle bento' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1220, protein = 26, carbohydrates = 220, fat = 26, fiber = 26, cooking_time = 900 WHERE description = 'Black bean plantain bowls' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1224, protein = 16, carbohydrates = 114, fat = 80, fiber = 8, cooking_time = 600 WHERE description = 'Elote-style vegetable tostadas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1696, protein = 64, carbohydrates = 84, fat = 128, fiber = 28, cooking_time = 600 WHERE description = 'Grilled halloumi and vegetables' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1920, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 600 WHERE description = 'Grilled Veggies and Gnocchi with Salsa Verde' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1341, protein = 38, carbohydrates = 186, fat = 51, fiber = 24, cooking_time = 1200 WHERE description = 'Katsu-style eggplant with stir-fried green beans and sweet peppers' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1052, protein = 28, carbohydrates = 170, fat = 18, fiber = 36, cooking_time = 600 WHERE description = 'Black bean and delicata squash bowls' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1280, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 600 WHERE description = 'Creamy Lemon Spinach-Ricotta Ravioli' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1218, protein = 34, carbohydrates = 146, fat = 58, fiber = 20, cooking_time = 600 WHERE description = 'Sweet potato fajitas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1290, protein = 39, carbohydrates = 109, fat = 78, fiber = 9, cooking_time = 600 WHERE description = 'Halloumi with pistachio rice' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1405, protein = 36, carbohydrates = 197, fat = 49, fiber = 13, cooking_time = 600 WHERE description = 'Kimchi jeon' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2034, protein = 38, carbohydrates = 250, fat = 80, fiber = 29, cooking_time = 2400 WHERE description = 'Strawberry Almond Oat Bars' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1500, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 600 WHERE description = 'Middle Eastern chickpea bowls' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1187, protein = 31, carbohydrates = 193, fat = 32, fiber = 6, cooking_time = 900 WHERE description = 'Bibim guksu' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 379, protein = 15, carbohydrates = 55, fat = 12, fiber = 8, cooking_time = 600 WHERE description = 'Lemon poppy seed overnight oats' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 377, protein = 13, carbohydrates = 49, fat = 16, fiber = 7, cooking_time = 600 WHERE description = 'Chocolate chip cookie dough overnight oats' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1764, protein = 66, carbohydrates = 294, fat = 42, fiber = 72, cooking_time = 1200 WHERE description = 'BBQ Vegetable Salad' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2245, protein = 76, carbohydrates = 239, fat = 120, fiber = 27, cooking_time = 600 WHERE description = 'Grilled tofu tacos' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 108, protein = 8, carbohydrates = 20, fat = 4, fiber = 8, cooking_time = 300 WHERE description = 'Okra with ginger soy sauce' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1352, protein = 34, carbohydrates = 135, fat = 77, fiber = 16, cooking_time = 900 WHERE description = 'Mushroom and herb shepherd''s pie' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1240, protein = 0, carbohydrates = 0, fat = 0, fiber = 0, cooking_time = 300 WHERE description = 'Mexicali black bean soup' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1278, protein = 50, carbohydrates = 162, fat = 32, fiber = 30, cooking_time = 600 WHERE description = 'Tofu poke bowl' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1153, protein = 24, carbohydrates = 122, fat = 67, fiber = 16, cooking_time = 900 WHERE description = 'Grilled eggplant sandwich' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1137, protein = 43, carbohydrates = 163, fat = 48, fiber = 37, cooking_time = 900 WHERE description = 'Avocado Breakfast Flatbreads with Pickled White Beans' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1268, protein = 29, carbohydrates = 143, fat = 62, fiber = 29, cooking_time = 600 WHERE description = 'Banana Nut Chia Pudding' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2032, protein = 96, carbohydrates = 280, fat = 76, fiber = 24, cooking_time = 600 WHERE description = 'Soba salad with grilled mushrooms and tofu' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2267, protein = 62, carbohydrates = 358, fat = 69, fiber = 28, cooking_time = 300 WHERE description = 'Cheesy Cabbage Tteokbokki' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1360, protein = 47, carbohydrates = 122, fat = 82, fiber = 30, cooking_time = 900 WHERE description = 'Grilled loaded nachos' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 720, protein = 34, carbohydrates = 96, fat = 22, fiber = 6, cooking_time = 1800 WHERE description = 'Hiyashi Chuka Ramen' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 2173, protein = 94, carbohydrates = 279, fat = 82, fiber = 24, cooking_time = 900 WHERE description = 'Sweet and Spicy Tofu With Soba Noodles' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1397, protein = 49, carbohydrates = 107, fat = 90, fiber = 8, cooking_time = 600 WHERE description = 'Chinese Stir-Fried Tomatoes and Eggs' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 787, protein = 143, carbohydrates = 13, fat = 8, fiber = 6, cooking_time = 15 WHERE description = 'Chocolate protein powder mix' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 344, protein = 44, carbohydrates = 0, fat = 10, fiber = 0, cooking_time = 15 WHERE description = 'Chocolate protein shake' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1125, protein = 54, carbohydrates = 117, fat = 58, fiber = 14, cooking_time = 15 WHERE description = 'Shredded Tofu and Shiitake Stir-Fry' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1104, protein = 40, carbohydrates = 108, fat = 60, fiber = 17, cooking_time = 15 WHERE description = 'Vegetarian Mushroom Shawarma Pitas' AND is_recipe = true AND calories = 0;
UPDATE food SET calories = 1699, protein = 121, carbohydrates = 72, fat = 114, fiber = 31, cooking_time = 1800 WHERE description = 'Tofu salad slaw with peanuts and nori' AND is_recipe = true AND calories = 0;

-- Summary: Updated 237 recipes with real nutritional data
