-- 9. ALIGN SCHEMA WITH ENTITY MAPPINGS
-- ddl-auto=validate surfaced drift between the V0-V7 migrations and the current
-- entity classes (local + shared GymCommonServices). This migration adds every
-- column the entities map that the tables were missing (added nullable so
-- existing rows are unaffected; Hibernate validation does not check nullability)
-- and corrects five column types that conflicted with the mappings.

-- messages.sender_id / receiver_id are usernames (String) in the shared Message
-- entity, not user FKs. Table is empty, so the cast is trivial.
ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_sender_id_fkey;
ALTER TABLE messages DROP CONSTRAINT IF EXISTS messages_receiver_id_fkey;
ALTER TABLE messages
    ALTER COLUMN sender_id TYPE VARCHAR(255) USING sender_id::text,
    ALTER COLUMN receiver_id TYPE VARCHAR(255) USING receiver_id::text;

-- Entities map these as LocalDateTime (timestamp without time zone).
ALTER TABLE inventory ALTER COLUMN purchase_date TYPE TIMESTAMP;
ALTER TABLE otps ALTER COLUMN end_time TYPE TIMESTAMP;
ALTER TABLE permissions ALTER COLUMN create_date TYPE TIMESTAMP;

-- Missing columns, generated by diffing Hibernate's expected schema against
-- information_schema.columns.
ALTER TABLE attendance_logs
    ADD COLUMN entity_id UUID,
    ADD COLUMN entity_type VARCHAR(255);

ALTER TABLE branches
    ADD COLUMN password_hash VARCHAR(255),
    ADD COLUMN username VARCHAR(255);

ALTER TABLE exercises
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN step_one_description VARCHAR(255),
    ADD COLUMN step_one_image VARCHAR(255),
    ADD COLUMN step_two_description VARCHAR(255),
    ADD COLUMN step_two_image VARCHAR(255),
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE expenses
    ADD COLUMN org_id UUID;

ALTER TABLE food
    ADD COLUMN calcium DOUBLE PRECISION,
    ADD COLUMN cholesterol DOUBLE PRECISION,
    ADD COLUMN cooking_time INTEGER,
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN fiber DOUBLE PRECISION,
    ADD COLUMN high_cholesterol BOOLEAN,
    ADD COLUMN high_fiber BOOLEAN,
    ADD COLUMN high_sodium BOOLEAN,
    ADD COLUMN iron DOUBLE PRECISION,
    ADD COLUMN keto_friendly BOOLEAN,
    ADD COLUMN key_ingredients TEXT,
    ADD COLUMN low_cholesterol BOOLEAN,
    ADD COLUMN low_sodium BOOLEAN,
    ADD COLUMN mono_unsaturated_fat DOUBLE PRECISION,
    ADD COLUMN poly_unsaturated_fat DOUBLE PRECISION,
    ADD COLUMN saturated_fat DOUBLE PRECISION,
    ADD COLUMN sodium DOUBLE PRECISION,
    ADD COLUMN sugar DOUBLE PRECISION,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE food_log
    ADD COLUMN serving_unit VARCHAR(255);

ALTER TABLE food_nutrient
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN derived_method VARCHAR(255),
    ADD COLUMN max_val DOUBLE PRECISION,
    ADD COLUMN median_val DOUBLE PRECISION,
    ADD COLUMN min_val DOUBLE PRECISION,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE food_portion
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN modifier VARCHAR(255),
    ADD COLUMN sequence_number INTEGER,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE inventory
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN description VARCHAR(255),
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE messages
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN sender_role VARCHAR(255),
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE nutrient
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN nutrient_rank INTEGER,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE organizations
    ADD COLUMN address_line_1 VARCHAR(255),
    ADD COLUMN address_line_2 VARCHAR(255),
    ADD COLUMN city VARCHAR(255),
    ADD COLUMN is_email_verified BOOLEAN,
    ADD COLUMN is_phone_verified BOOLEAN,
    ADD COLUMN number_of_owners INTEGER,
    ADD COLUMN owner_contact_email VARCHAR(255),
    ADD COLUMN owner_name VARCHAR(255),
    ADD COLUMN password_hash VARCHAR(255),
    ADD COLUMN phone VARCHAR(255),
    ADD COLUMN pincode VARCHAR(255),
    ADD COLUMN state VARCHAR(255),
    ADD COLUMN username VARCHAR(255);

ALTER TABLE otps
    ADD COLUMN branch_id UUID,
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN org_id UUID,
    ADD COLUMN start_time TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE payments
    ADD COLUMN branch_id UUID,
    ADD COLUMN member_id UUID,
    ADD COLUMN org_id UUID;

ALTER TABLE plans
    ADD COLUMN description VARCHAR(255),
    ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN sort_order INTEGER;

ALTER TABLE roles
    ADD COLUMN created_by UUID,
    ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE trainer_ratings
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE user_diet_plans
    ADD COLUMN attachment_url VARCHAR(255),
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN is_deleted BOOLEAN DEFAULT false,
    ADD COLUMN premium_user_id UUID,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE users
    ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE weekly_workout_plans
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE workout_exercises
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN updated_at TIMESTAMPTZ;

ALTER TABLE workouts
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN deleted_at TIMESTAMPTZ,
    ADD COLUMN description VARCHAR(255),
    ADD COLUMN image_url VARCHAR(255),
    ADD COLUMN mandatory_exercises INTEGER,
    ADD COLUMN updated_at TIMESTAMPTZ;
