spring.application.name=GymUserManagement

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/gymmanagment
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


app.cors.allowed-origins=*
# JWT Configuration
# 256-bit secret key (32 bytes)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
jwt.refreshExpiration=604800000

# Server Configuration
server.port=8080

# Twilio Configuration
twilio.account.sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.phone.number=YOUR_TWILIO_PHONE_NUMBER

# GymCommonServices Compatibility
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhinavsahu120@gmail.com
spring.mail.password=oodcickrxmenrrzj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
